# These are supported funding model platforms

github: ctlos
patreon: ctlos
open_collective: ctlos
ko_fi: creio
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://yoomoney.ru/to/410011749909586
custom: https://www.buymeacoffee.com/creio
