#!/usr/bin/bash

print_info() {
    # info title
    # info underline
    # info "OS" distro
    prin "$(color 4)ctlos.github.io"
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "WM" wm
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "Terminal Font" term_font
    info "Font" font
    #info "CPU" cpu
    #info "GPU" gpu
    #info "CPU Usage" cpu_usage
    #info "Battery" Battery
    info "Disk" disk
    info "Local IP" local_ip
    # info "Public IP" public_ip
    # info "Song" song
    #prin "Weather" "$(curl wttr.in/?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF) " ("a")"} /,/ {a=$0}')"
    # prin "Weather" "$(curl wttr.in/60.04,30.32?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF)}')"
    # prin "Weather" "$(curl wttr.in/Gomel?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF)}')"
    info line_break
    info cols
    # info line_break
}

kernel_shorthand="on"
distro_shorthand="off"
os_arch="off"
uptime_shorthand="on"
shell_path="off"
shell_version="on"
speed_type="bios_limit"
speed_shorthand="on"
cpu_brand="off"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
gpu_type="all"
gtk_shorthand="on"
gtk2="on"
gtk3="on"
disk_show=('/home')
disk_subtitle="mount"
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="-"
block_range=(0 7)
color_blocks="on"
block_width=3
block_height=1
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=(distro)
# ascii_bold="on"
gap=3
config_version="3.3.0"
