#!/usr/bin/env bash

looping=$1

if [ -z $looping ]
then
  looping=~/.wall/heart.gif
fi

#### 20% cpu gif, best result, convert mp4 -> gif:
## ffmpeg -i .wall/heart.mp4 .wall/heart.gif
xwinwrap -b -fs -sp -fs -ov -ni -nf -- mpv -wid WID --no-config --keepaspect=no --loop --no-border --x11-bypass-compositor=no --aid=no --hwdec=auto --really-quiet $looping

#### 40% cpu mp4
# xwinwrap -b -fs -sp -fs -ov -ni -nf -- mpv -wid WID --no-config --keepaspect=no --loop --no-border --vd-lavc-fast --x11-bypass-compositor=no --aid=no --vo=xv --hwdec=auto --really-quiet $looping

#### 60% cpu gif
#### gifsicle --resize 1366x768 wl7.gif -o bg.gif
# xwinwrap -b -fs -sp -fs -ov -ni -nf -- gifview -w WID $looping -a
