#! /bin/bash
#

# For Pulseaudio with ALSA:
ffmpeg -y \
-f x11grab \
-framerate 30 \
-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
-i :0.0 \
-f alsa -i default \
-r 30 \
-c:v libx264rgb -crf 0 -preset ultrafast -c:a flac \
-y ~/Videos/screen/output.mkv

# For ALSA:
# ffmpeg -y \
# -f x11grab \
# -s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
# -i :0.0 \
# -thread_queue_size 1024 \
# -f alsa -ar 44100 -i hw:1 \
# -c:v libx264 -r 30 -c:a flac \
# -y ~/Videos/screen/output.mkv