#! /bin/bash
#

# For Pulseaudio with ALSA:
ffmpeg -y \
-f x11grab \
-framerate 30 \
-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
-i :0.0 \
-f alsa -ar 44100 -i default \
-r 30 \
-c:v libx264rgb -crf 23 -preset ultrafast -c:a aac \
-y ~/Videos/screen/output.mkv