#!/bin/bash

# Draw a floating
read -r X Y W H < <(slop -f "%x %y %w %h" -b 4 -t 0 -q)

# 🔸 Подберите эти значения под ваш шрифт в alacritty.toml/yml
CELL_WIDTH=10    # ширина одного символа в пикселях
CELL_HEIGHT=23  # высота строки (глиф + line padding)

(( COLS = W / CELL_WIDTH ))
(( ROWS = H / CELL_HEIGHT ))

alacritty \
  -o "window.dimensions.columns=$COLS" \
  -o "window.dimensions.lines=$ROWS" \
  -o "window.position.x=$X" \
  -o "window.position.y=$Y" &