#!/bin/bash

# Below command will backup everything inside the project folder
git add .

# Give a comment to the commit if you want
echo "####################################"
echo "Write your commit comment! $(date +%Y.%m.%d) Update:"
echo "####################################"

read input

# Committing to the local repository with a message containing the time details and commit text

git commit -a -m "$(date +%Y.%m.%d) Update $input"

# Push the local files to github

git push


echo "################################################################"
echo "###################    Git Push Done      ######################"
echo "################################################################"