#!/bin/bash

echo -e "\033[0;32mDeploy to Git Repo...\033[0m"

git add .
msg="$(date +%d.%m.%Y) Update"
if [ $# -eq 1 ]
  then msg="$(date +%d.%m.%Y) Update $1"
fi
git commit -a -m "$msg"
git push
echo "Git Push Done!"
