#!/bin/bash
# https://archlinux.org/mirrorlist/
# https://archlinux.org/mirrors/status/

# reflector --list
## https://ipapi.co/country | http://ip-api.com/line?fields=country | https://ipwhois.app/line/?objects=country

# Check for root
# if [[ $EUID -ne 0 ]]; then
#   echo "run root | sudo"; exit 1
# fi

if [ "$(which curl)" != "curl not found" ]; then
  check_country=$(curl -s https://ipinfo.io/country)
fi

# if [[ $check_country == 'BY' ]]; then
# cat <<LOL >/etc/pacman.d/mirrorlist
# #Server = rsync://ftp.byfly.by/pub/archlinux/\$repo/os/\$arch
# #Server = rsync://mirror.datacenter.by/pub/archlinux/\$repo/os/\$arch

# # Server = https://ftp.byfly.by/pub/archlinux/\$repo/os/\$arch
# Server = https://mirror.datacenter.by/pub/archlinux/\$repo/os/\$arch

# LOL
# fi

if [ "$1" = "-lc" ]; then
  # mirrors -lc
  sudo reflector --verbose -p "https,http" -c "ru,kz,pl,de,$check_country" --sort rate -l 20 -f 10 --threads 5 --save /etc/pacman.d/mirrorlist
elif [ "$1" = "-c" ]; then
  # mirrors -c
  sudo reflector --verbose -p "https,http" -c "ru,$check_country" --sort rate --l 10 -threads 5 --save /etc/pacman.d/mirrorlist
else
  # mirrors
  sudo reflector --verbose -p "https,http" --sort rate -l 20 -f 10 --threads 5 --save /etc/pacman.d/mirrorlist
  # reflector --verbose -p "https,http" --sort score -f 5 --threads 5 --save /etc/pacman.d/mirrorlist
fi

cat /etc/pacman.d/mirrorlist

sudo pacman -Syy --noconfirm