#!/usr/bin/env bash

wm=$(wmctrl -m 2>/dev/null | grep "Name" | cut -d " " -f2)
[[ -z $wm ]] && wm="$(xprop -root -notype _NET_WM_NAME | awk 'END{print $3}' | tr -d \")" || wm=$wm

[[ $wm == i3 ]] && Logout_command="i3-msg 'exit'" || Logout_command="openbox --exit"
Suspend_command="$HOME/.bin/multilock.sh -s blur & systemctl suspend"
Hibernate_command="systemctl hibernate"
Reboot_command="systemctl reboot"
Poweroff_command="systemctl poweroff"
Exit_command="exit 0"

options=$'Logout\nSuspend\nHibernate\nReboot\nPoweroff\nExit'

rofi_command="rofi -hide-scrollbar -tokenize -lines 6 -eh 1 -width 25 -location 0 -xoffset 0 -yoffset 0 -padding 20 -disable-history"

eval \$"$(echo "$options" | $rofi_command -dmenu -i -p "SYSTEM")_command"
