#!/bin/sh
#
# ufetch-ctlos - tiny system info for arch

## INFO

# user is already defined
host="$(hostname)"
os='Ctlos Linux'
kernel="$(uname -r)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi

## DEFINE COLORS

# probably don't change these
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# you can change these
lc="${reset}${bold}${cyan}"		# labels
nc="${reset}${bold}${cyan}"		# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${bold}${cyan}"		# first color
c1="${reset}${cyan}"			# second color

## OUTPUT

cat <<EOF

${c0}        /\        ${nc}${USER}${c1}@${nc}${host}${reset}
${c0}       /  \       ${lc}OS:        ${c1}${os}${reset}
${c0}      /    \      ${lc}KERNEL:    ${c1}${kernel}${reset}
${c0}     /  ${c1}__  \     ${lc}UPTIME:    ${c1}${uptime}${reset}
${c1}    /  (**)  \    ${lc}PACKAGES:  ${c1}${packages}${reset}
${c1}   //__|  |__\\\\   ${lc}SHELL:     ${c1}${shell}${reset}
${c1}  ///        \\\\\  ${lc}${envtype}:        ${c1}${WM}${reset}

EOF