#!/bin/bash

srcsh=${0##*/}

# Проверка: если процесс уже есть — убиваем всё и выходим (режим переключателя)
if pgrep -f "rx_vis" > /dev/null; then
  killall cava
  pkill -f "devilspie /tmp/rx_vis.ds"
  pkill -f "$srcsh"
  exit
fi

# Параметры экрана
BAR_HEIGHT_SHOW=960
BAR_HEIGHT_HIDE=970

# 1. Запуск Alacritty
alacritty --config-file $HOME/.config/alacritty/rx_vis.toml --class rx_vis,rx_vis --title rx_vis -e cava &

# 2. Ждем окно (без этого xdo выдает ошибку)
xdotool search --sync --onlyvisible --class "rx_vis" > /dev/null
WIN_ID=$(xdotool search --class "rx_vis" | tail -1)

# 3. Конфиг Devilspie (убираем декорации и делаем доком)
if [[ $(command -v devilspie) ]]; then
echo "(and
  (is (window_class) \"rx_vis\")
  (begin
    (stick)
    (above)
    (pin)
    (undecorate)
    (skip_pager)
    (skip_tasklist)
    (wintype \"dock\")
    (geometry \"1920x170+0+920\")
  )
)" > /tmp/rx_vis.ds
devilspie /tmp/rx_vis.ds > /dev/null &
fi

# Команды управления
SHOW_CMD="xdo show $WIN_ID"
HIDE_CMD="xdo hide $WIN_ID"

get_y_position() {
  xdotool getmouselocation --shell | grep Y | cut -d= -f2
}

hidden=false
eval $SHOW_CMD

# Основной цикл
while :; do
  y_loc=$(get_y_position)

  if (( y_loc < BAR_HEIGHT_SHOW )) && [ "$hidden" = true ]; then
    eval $SHOW_CMD
    hidden=false
  fi

  if (( y_loc >= BAR_HEIGHT_HIDE )) && [ "$hidden" = false ]; then
    eval $HIDE_CMD
    hidden=true
  fi
  sleep 0.1
done