#!/usr/bin/env bash
# George Ornbo (shapeshed) http://shapeshed.com
# License - http://unlicense.org
#
# Fixes a corrupt .zhistory file

mv ~/.zhistory ~/.zhistory_bad
strings ~/.zhistory_bad > ~/.zhistory
fc -R ~/.zhistory
rm ~/.zhistory_bad
