#! /bin/sh

sxhkd -c $HOME/.config/sxhkd/sxhkdrc.bspwm &

setxkbmap -layout us,ru -option "grp:win_space_toggle,grp_led:scroll" &
picom -b --config ~/.config/picom.conf &
hsetroot -fill $HOME/.wall/Crow.png &
# hsetroot -add '#b89ca8' -add '#202029' -gradient 130 &
# hsetroot -solid '#35303e' &
$HOME/.config/bspwm/polybar/launch.sh &
tint2 -c ~/.config/tint2/tray.tint2rc &
dunst &
numlockx &
xsettingsd &
# pulseaudio --start &
# mpd &
/usr/lib/xfce-polkit/xfce-polkit &
redshift-gtk &
xfce4-power-manager &
caffeine &
# udiskie -t &
# nm-applet &
clipit &
# greenclip daemon &
# unclutter &
# megasync &
telegram-desktop &
