#!/bin/sh

focused=$(xrdb -query all | grep color7 | cut -f2)
normal=$(xrdb -query all | grep color8 | cut -f2)

bspc monitor -d TERM CODE WEB FILES MEDIA EXTRA

bspc config focused_border_color  "$focused"
bspc config normal_border_color   "$normal"
bspc config border_width          2
bspc config window_gap            10
bspc config focus_follows_pointer false
bspc config top_padding           35
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config single_monocle        true

bspc rule -a code-oss desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a Google-chrome desktop='^3' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=fullscreen follow=on

xsetroot -cursor_name left_ptr
hsetroot -fill ~/.wall/wl.jpg &
tint2 -c ~/.config/tint2/button.tint2rc &
tint2 -c ~/.config/tint2/hide_tray.tint2rc &
$HOME/.config/bspwm/polybar/launch.sh &
dunst &
$HOME/.config/bspwm/bin/floating_noborder &
picom -b --config ~/.config/picom.conf &
urxvtd -q -o -f &
numlockx on &
xsettingsd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11,secrets &
setxkbmap -layout us,ru -option "grp:win_space_toggle,grp_led:scroll" -option "compose:ralt" &
unclutter --timeout 2 &
redshift -c ~/.config/redshift.conf &
greenclip daemon &
# syncthing &
