#!/usr/bin/env bash

color0=$(xrdb -query | egrep -m1 '^\*\.?color0:' | awk '{print $NF}')
color1=$(xrdb -query | egrep -m1 '^\*\.?color1:' | awk '{print $NF}')
color2=$(xrdb -query | egrep -m1 '^\*\.?color2:' | awk '{print $NF}')
color3=$(xrdb -query | egrep -m1 '^\*\.?color3:' | awk '{print $NF}')
color4=$(xrdb -query | egrep -m1 '^\*\.?color4:' | awk '{print $NF}')
color5=$(xrdb -query | egrep -m1 '^\*\.?color5:' | awk '{print $NF}')
color6=$(xrdb -query | egrep -m1 '^\*\.?color6:' | awk '{print $NF}')
color7=$(xrdb -query | egrep -m1 '^\*\.?color7:' | awk '{print $NF}')

color8=$(xrdb -query | egrep -m1 '^\*\.?color8:' | awk '{print $NF}')
color9=$(xrdb -query | egrep -m1 '^\*\.?color9:' | awk '{print $NF}')
color10=$(xrdb -query | egrep -m1 '^\*\.?color10:' | awk '{print $NF}')
color11=$(xrdb -query | egrep -m1 '^\*\.?color11:' | awk '{print $NF}')
color12=$(xrdb -query | egrep -m1 '^\*\.?color12:' | awk '{print $NF}')
color13=$(xrdb -query | egrep -m1 '^\*\.?color13:' | awk '{print $NF}')
color14=$(xrdb -query | egrep -m1 '^\*\.?color14:' | awk '{print $NF}')
color15=$(xrdb -query | egrep -m1 '^\*\.?color15:' | awk '{print $NF}')
