#!/bin/sh

set -e

daemon=${1:?}
state="%{F#AEB4C6}$1%{F-}"
cmd="$(systemctl status $daemon | grep -i ": active" 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#B48EAD}$1%{F-}"

echo "%{F#AEB4C6}${state}%{F-}"
exit 0
