#!/bin/sh

set -e

daemon=${1:?}
state="%{F#AEB4C6}off%{F-}"
cmd="$(systemctl status $daemon | grep -i run 2>/dev/null || echo '')"

[[ "$cmd" ]] && state="%{F#BF616A}on%{F-}"

echo "%{F#B48EAD}${daemon}%{F-} ${state}"
exit 0
