#!/bin/sh

# terminal
super + {Return, @space}
	urxvt

# program launcher
super + d
  $HOME/.config/bspwm/bin/run_dmenu

# programs
# variables in .bash_profile
super + shift + {f,v,m,t}
  {\
  $TERMINAL -e $FMANAGER,\
  $TERMINAL -e $EDITOR,\
  $TERMINAL -e ncmpcpp,\
  $TERMINAL -e rtorrent
\}

# browsers
super + alt + f
	firefox

super + alt + g
	google-chrome-stable

# scripts
super + shift + r
  redshift_toggle

ctrl + shift + l
  lock


# brightness keybindings
XF86MonBrightness{Up,Down}
  brightnessctl s 5%{+,-} &

# media keys
XF86Audio{Next,Prev,Play,Stop}
  mpc {next,prev,toggle,stop}

# volume
XF86AudioRaiseVolume
	pactl set-sink-volume 0 +5%

XF86AudioLowerVolume
  pactl set-sink-volume 0 -5%

XF86AudioMute
  pactl set-sink-mute 0 toggle

# screenshot keybindings
Print
  scrot "$HOME/Pictures/Screenshots/%Y-%m-%d-%H-%M-%S.png" && \
	notify-send "Screenshot captured"
ctrl + Print
  scrot -C

# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

# gaps
super + shift + alt  + g
  bspc config window_gap 0
super + shift + g
  bspc config window_gap 10

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,alt + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + b
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,alt + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
