#!/usr/bin/sh

xset -b
# wmname LG3D &

tint2 -c ~/.config/tint2/button.tint2rc &
tint2 -c ~/.config/tint2/hide_tray.tint2rc &
[[ $(command -v polybar) ]] && sh ~/.config/polybar/launch.sh &
# hsetroot -add '#2c3539' -add '#b89ca8' -gradient 130 &
# hsetroot -tile input.jpg -contrast 0.6 &
hsetroot -fill ~/.wall/ctld.png &
# sh ~/.bin/pscircle-dark.sh &
picom -b --config ~/.config/picom.conf &
# picom -b --experimental-backends --config ~/.config/picom_blur.conf &
# flashfocus &
[[ $(command -v thunar) ]] && thunar --daemon &
urxvtd -q -o -f &
alttab -fg "#9baec8" -bg "#161720" -frame "#5a74ca" -t 128x128 -i 128x48 -d 2 -theme Qogir-dark -font "xft:ClearSansMedium:size=9:antialias=false" -pk "Left" -nk "Right" &
numlockx on &
xsettingsd &
# xfsettingsd &
xfce4-power-manager &
# /usr/lib/xfce4/notifyd/xfce4-notifyd &
dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11,secrets &
setxkbmap -layout us,ru -option "grp:win_space_toggle,grp_led:scroll" -option "compose:ralt" &
# setxkbmap -layout us,ru -option "grp:alt_shift_toggle,grp_led:scroll" &
unclutter --timeout 2 &
redshift -c ~/.config/redshift.conf &
greenclip daemon &
# parcellite &
# animatebg -v https://www.youtube.com/watch?v=N1FuK9KC1vc &
# ~/.bin/mpv_bg &
# sh -c ~/.bin/urxvt_bg &
# sh -c ~/.conky/start.sh &

#glava &

# jgmenu_run start &
# cornora -bl "skippy-xd" -tl "rofi -show run" &
# (sleep 2; caffeine) &
# (sleep 5; nm-applet) &
# (sleep 2; volumeicon) &
# udiskie -t &
# sh -c "kunst --music_dir /media/files/music --size 250x250 --x 1080 --y 60"

